# Generated by Django 4.1.7 on 2023-03-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='name',
            new_name='title',
        ),
    ]
